# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install gpt-2-simple
    - name: Run neural
      run: |
        python3 main.py
    - name: Run ls
      run: |
        ls -ln
    - name: Run cat
      run: |
        cat export/gpt_2_gen_texts.txt

    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: commit
      run: |
        # Stage the file, commit and push
        git add checkpoint
        git add export
        git commit -m "new date commit"
        git push origin master