# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Cron

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 9 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install gpt-2-simple
      
    - name: Run neural
      run: |
        python3 main.py
    - name: Run ls
      run: |
        ls -ln
      
    - name: Run cat
      run: |
        cat export/gpt_2_gen_texts.txt
      
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Плановое обучение"
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}